### ISSUE TITLE
Wrong message output on intent detection

### ISSUE THREAD

**Issue by sfratini** [IBM/personal-wealth-portfolio-mgt-bot#11]
Hi! There is a related issue that shows how on many inputs the message that is shown is wrong. I am using the debug.html URL and found that the bot is detecting the intents correctly but is using always the anything_else_main dialog branch. Even on the successful ones. Example:

Input:

```
 "input": {
    "text": "show me my portfolio"
  },
```

Output:

  ```
"intents": [
    {
      "intent": "portfolio_holdings",
      "confidence": 1
    }
  ],
  "entities": [
    {
      "entity": "portfolio",
      "location": [
        11,
        20
      ],
      "value": "portfolio",
      "confidence": 1
    }
  ],
  "input": {
    "text": "show me my portfolio"
  },
  "output": {
    "text": "Your portfolio consists of 1500 shares of IBM, 5000 shares of GE, 5000 shares of F, 1800 shares of BAC",
    "nodes_visited": [
      "Anything else - main"
    ],
    "log_messages": []
  },
```

And in the wrong ones, it is showing the "I'm sorry, but I didn't understand you" which is the generic default response. 

Input:

```
"input": {
    "text": "What's my portfolio worth?"
  },
```

Output:

 ```
"intents": [
    {
      "intent": "portfolio_valuation",
      "confidence": 1
    }
  ],
  "entities": [
    {
      "entity": "portfolio",
      "location": [
        10,
        19
      ],
      "value": "portfolio",
      "confidence": 1
    }
  ],
  "input": {
    "text": "What's my portfolio worth?"
  },
  "output": {
    "text": "I'm sorry, but I didn't understand you",
    "nodes_visited": [
      "Anything else - main"
    ],
    "log_messages": []
  },
```

It seems to be that the bot it is actually using always the node "Anything else - main" and overriding the output.text. 

Is this expected?

**Comment by ljbennett62** [comment]
@sfratini - it looks like someone added additional intents to the workspace that was not be taken care in the code. Each time a new intent is added - the code needs to make sure it recognizes it.

**Comment by ljbennett62** [comment]
if you look at the Conversation .json file or through the IBM Cloud Conversation Tooling - you can see what questions you can ask - and you can customize it.
