### ISSUE TITLE
Custom responses seems to be overriden

### ISSUE THREAD

**Issue by sfratini** [IBM/personal-wealth-portfolio-mgt-bot#12]
Hey, so I am just trying to understand how the integration with the Investment API and the Simulated Analytics work. I see that the dialog for the S&P branch responds with something like:

"If the S&P 500 drops 2% your portfolio could drop 1.5% or $12,341"

With seems hardcoded, however the bot answers with something different which I assume comes from the API. 

What I couldn't find is:
a) Where are these hooks either develop or configured
b) Why do we have hardcoded strings. Is it just to have a placeholder and we just ignore them?

Thanks!

**Comment by samuelcwl** [comment]
@sfratini , did you ever get an update on this? I'm running into this issue as well.

**Comment by sfratini** [comment]
@samuelcwl  It is the expected behavior. If you take a look at the code, it is actually ignoring some of the custom parameters. There is 2 features enabled in the demo and you can see that if you want to enable the rest you need to do some work. I still have the demo, but eventually we made a working code with BotBuilder.
