### ISSUE TITLE
Unable to deply the app to IBM Cloud

### ISSUE THREAD

**Issue by hkgian** [IBM/personal-wealth-portfolio-mgt-bot#20]
I tried multiple times to deploy this app but I face the following error message:
Error processing app files: Error uploading application.
Server error, status code: 500, error code: 150007, message: Failed to perform blobstore operation after three retries.
<img width="969" alt="image" src="https://user-images.githubusercontent.com/8159191/35436068-4c30c634-028d-11e8-9394-01c597cd394d.png">

Please let me know if you are able to reproduce the error.

**Comment by ljbennett62** [comment]
@hkgian - made some fixes - please give it a try - i will close this for now - reopen if you run into it again.
