### ISSUE TITLE
Wealth Management Create Project fails

### ISSUE THREAD

**Issue by lemacomb** [IBM/personal-wealth-portfolio-mgt-bot#21]
Using the FinTech Console starter kit, I attempted to create a wealth management project.  The creation failed.
![chatbotprojectfailed](https://user-images.githubusercontent.com/30877682/36390526-5b80a6e4-1571-11e8-8a13-0c55a0e53ec2.JPG)

**Comment by ljbennett62** [comment]
I have updated the code - take another try.
