### ISSUE TITLE
The conversation workspace should be imported automatically

### ISSUE THREAD

**Issue by l2fprod** [IBM/personal-wealth-portfolio-mgt-bot#3]
It could be done with a custom toolchain or directly by the application using the Watson Conversation API (this repo imports the json on startup - https://github.com/IBM-Bluemix/insurance-bot/blob/dev/config/bot.js#L113)

**Comment by stevemart** [comment]
We did this for our banking chatbot too, see https://github.com/IBM/watson-banking-chatbot/blob/master/lib/watson-conversation-setup.js as we used the node-js SDK, it should be a near drop in replacement you can re-use.

**Comment by ljbennett62** [comment]
let me take a look at what you did Steve in your banking chatbot and see how i could update this to make it more streamline
