### ISSUE TITLE
Is there a demo script detailing what we can ask the bot?

### ISSUE THREAD

**Issue by l2fprod** [IBM/personal-wealth-portfolio-mgt-bot#5]
Looking at the conversation intents, I tried "What's my portfolio worth?" but the bot said "I'm sorry, but I didn't understand you".

Are there instructions to use the bot? What intents are supposed to work?

**Comment by ljbennett62** [comment]
There isn't a script - but the two suggested questions are given when you start the app - let me try to replicate your question - as I would think that would work. The intents are: 1) hello 2) portfolio_holdings (meaning asking how your portfolio is) 3) portfolio_impact_analysis (only applies to the S&P 500 changes)

**Comment by ljbennett62** [comment]
This is fixed as part of issue #11
