### ISSUE TITLE
Auto deploy did not run the app successfully 

### ISSUE THREAD

**Issue by nching3975** [IBM/personal-wealth-portfolio-mgt-bot#6]
Auto deploy to bluemix missing entry for Simulated Instrument Analytics in VCAP_SERVICES
"What is the impact on my portfolio if the S&P 500 goes down 5%?"
Does not return a response for the auto deployed app, but running the app locally, it does work.  

WORKSPACE_ID set in runtime env was not used, pushed a change to set the string in /lib/api/conversation.js and the conversation started (intro text, and responses to hello and How are my portfolio listing?)

**Comment by ljbennett62** [comment]
Let's talk Monday - but we don't want to hard code env vars values in the actual source code.

**Comment by nching3975** [comment]
@ljbennett62 
I tried the auto deploy again in bluemix production, using the configuration instructions on this site, and it worked perfectly.  I must have made some mistakes the first time.  Closing this issue.
